# Generated by Django 6.0.4 on 2026-05-10 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set(),
        ),
    ]
